{% set name = "ticker" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/achannarasappa/ticker/archive/v{{ version }}.tar.gz
  sha256: e5adf107c1a38e9e5235a654eeede491c9dc01e25460270d092e937de3a16d68

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - ticker --help

about:
  home: https://github.com/achannarasappa/ticker
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal stock ticker with live updates and position tracking
  dev_url: https://github.com/achannarasappa/ticker

extra:
  recipe-maintainers:
    - danielnachun
