schema_version: 1

context:
  version: "5.2.0"

package:
  name: ticker
  version: ${{ version }}

source:
  url: https://github.com/achannarasappa/ticker/archive/v${{ version }}.tar.gz
  sha256: e2cfb09173cce87cb68c42331a6d4e23f5fd6135980e17c2dd37bfd23432cea3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - ticker --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal stock ticker with live updates and position tracking
  homepage: https://github.com/achannarasappa/ticker
  repository: https://github.com/achannarasappa/ticker

extra:
  recipe-maintainers:
    - danielnachun
